# Generated by Django 3.0.8 on 2020-09-26 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votingapp', '0002_auto_20200926_0020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='votes',
            new_name='no_votes',
        ),
    ]
